import { expect } from "@playwright/test";
import { createBdd } from "playwright-bdd";
import { ensureModeSelectorVisible, getUniqueCampaignName, waitForModalOpen, waitForModalClose, loginAs, waitForWorldUpdated, waitForPlanningMode } from "../helpers";

const { When, Then } = createBdd();
// Note: "the admin navigates to the World Entities planning screen" is defined in world-create.steps.ts

When("world {string} exists", async ({ page }, worldName: string) => {
  // Make world name unique per worker to avoid conflicts when tests run in parallel
  // For "Eldoria" and "NoSplashWorld", use unique names to ensure test isolation
  const uniqueWorldName = 
    worldName === "Eldoria" || worldName === "NoSplashWorld" 
      ? getUniqueCampaignName(worldName) 
      : worldName;
  
  // Ensure user is logged in first
  const logoutButton = page.getByRole("button", { name: "Log out" });
  const isLoggedIn = await logoutButton.isVisible({ timeout: 1000 }).catch(() => false);
  if (!isLoggedIn) {
    await loginAs(page, "admin", "admin");
  }
  
  await ensureModeSelectorVisible(page);

  const worldContextTablist = page.getByRole("tablist", { name: "World context" });
  // Check for both unique name and base name (for backwards compatibility)
  let hasWorldTab = await worldContextTablist
    .getByRole("tab", { name: uniqueWorldName })
    .isVisible()
    .catch(() => false);
  
  if (!hasWorldTab && (worldName === "Eldoria" || worldName === "NoSplashWorld")) {
    // Also check for base name
    hasWorldTab = await worldContextTablist
      .getByRole("tab", { name: worldName })
      .isVisible()
      .catch(() => false);
  }

  if (!hasWorldTab) {
    // Open the Snapp menu dropdown
    const snappMenuButton = page.getByRole("button", { name: /^Snapp/i });
    await snappMenuButton.click();
    
    // Click "Create world" from the dropdown menu
    await page.getByRole("button", { name: "Create world" }).click();
    
    // Wait for modal to open using transition event
    await waitForModalOpen(page, "world", 5000);
    
    // Fill the form
    await page.getByLabel("World name").fill(uniqueWorldName);
    await page.getByLabel("Description").fill("Autogenerated world for tests.");
    
    // Submit
    const saveButton = page.getByRole("button", { name: "Save world" });
    await expect(saveButton).toBeEnabled({ timeout: 2000 });
    await saveButton.click();
    
    // Wait for either modal to close OR world to appear
    const dialog = page.getByRole("dialog", { name: "Create world" });
    try {
      await Promise.race([
        waitForModalClose(page, "world", 8000),
        expect(worldContextTablist.getByRole("tab", { name: uniqueWorldName })).toBeVisible({ timeout: 8000 }),
        expect(dialog).toBeHidden({ timeout: 8000 })
      ]);
    } catch (raceError) {
      // Race timed out - continue to check state
    }
    
    // Verify world was created
    await expect(
      worldContextTablist.getByRole("tab", { name: uniqueWorldName })
    ).toBeVisible({ timeout: 3000 });
    
    // Store the unique name in page context for other steps to use
    await page.evaluate((name) => {
      (window as any).__testWorldName = name;
    }, uniqueWorldName);
  } else {
    // World already exists - store the name we found
    const foundName = hasWorldTab ? uniqueWorldName : worldName;
    await page.evaluate((name) => {
      (window as any).__testWorldName = name;
    }, foundName);
    
    // For "NoSplashWorld", ensure it has no splash image
    // We'll clear it when the world is selected in the next step
    // (This avoids complex state management here)
  }
});

When("world {string} exists and is selected", async ({ page }, worldName: string) => {
  // First ensure the world exists (reuse existing logic)
  // Make world name unique per worker to avoid conflicts when tests run in parallel
  const uniqueWorldName = 
    worldName === "Eldoria" || worldName === "NoSplashWorld" 
      ? getUniqueCampaignName(worldName) 
      : worldName;
  
  // Ensure user is logged in first
  const logoutButton = page.getByRole("button", { name: "Log out" });
  const isLoggedIn = await logoutButton.isVisible({ timeout: 1000 }).catch(() => false);
  if (!isLoggedIn) {
    await loginAs(page, "admin", "admin");
  }
  
  await ensureModeSelectorVisible(page);

  const worldContextTablist = page.getByRole("tablist", { name: "World context" });
  // Check for both unique name and base name (for backwards compatibility)
  let hasWorldTab = await worldContextTablist
    .getByRole("tab", { name: uniqueWorldName })
    .isVisible()
    .catch(() => false);
  
  if (!hasWorldTab && (worldName === "Eldoria" || worldName === "NoSplashWorld")) {
    // Also check for base name
    hasWorldTab = await worldContextTablist
      .getByRole("tab", { name: worldName })
      .isVisible()
      .catch(() => false);
  }

  if (!hasWorldTab) {
    // Open the Snapp menu dropdown
    const snappMenuButton = page.getByRole("button", { name: /^Snapp/i });
    await snappMenuButton.click();
    
    // Click "Create world" from the dropdown menu
    await page.getByRole("button", { name: "Create world" }).click();
    
    // Wait for modal to open using transition event
    await waitForModalOpen(page, "world", 5000);
    
    // Fill the form
    await page.getByLabel("World name").fill(uniqueWorldName);
    await page.getByLabel("Description").fill("Autogenerated world for tests.");
    
    // Submit
    const saveButton = page.getByRole("button", { name: "Save world" });
    await expect(saveButton).toBeEnabled({ timeout: 2000 });
    await saveButton.click();
    
    // Wait for either modal to close OR world to appear
    const dialog = page.getByRole("dialog", { name: "Create world" });
    try {
      await Promise.race([
        waitForModalClose(page, "world", 8000),
        expect(worldContextTablist.getByRole("tab", { name: uniqueWorldName })).toBeVisible({ timeout: 8000 }),
        expect(dialog).toBeHidden({ timeout: 8000 })
      ]);
    } catch (raceError) {
      // Race timed out - continue to check state
    }
    
    // Verify world was created
    await expect(
      worldContextTablist.getByRole("tab", { name: uniqueWorldName })
    ).toBeVisible({ timeout: 3000 });
    
    // Store the unique name in page context for other steps to use
    await page.evaluate((name) => {
      (window as any).__testWorldName = name;
    }, uniqueWorldName);
  } else {
    // World already exists - store the name we found
    const foundName = hasWorldTab ? uniqueWorldName : worldName;
    await page.evaluate((name) => {
      (window as any).__testWorldName = name;
    }, foundName);
  }
  
  // Now select the world (reuse existing selection logic)
  // Get the unique world name if it was stored, otherwise use what we found
  let finalWorldName = uniqueWorldName;
  if (worldName === "Eldoria" || worldName === "NoSplashWorld") {
    try {
      const storedName = await page.evaluate(() => {
        return (window as any).__testWorldName;
      });
      if (storedName) {
        finalWorldName = storedName;
      }
    } catch {
      // Use uniqueWorldName we already have
    }
  }

  // Try unique name first, then fall back to base name
  let worldTab = worldContextTablist.getByRole("tab", { name: finalWorldName });
  let exists = await worldTab.isVisible().catch(() => false);
  
  if (!exists && (worldName === "Eldoria" || worldName === "NoSplashWorld")) {
    // Fall back to base name for backwards compatibility
    worldTab = worldContextTablist.getByRole("tab", { name: worldName });
    exists = await worldTab.isVisible().catch(() => false);
  }
  
  if (exists) {
    // Set up event listener BEFORE clicking
    const planningModePromise = waitForPlanningMode(page, 5000);
    
    await worldTab.click();
    
    // Wait for planning mode to activate (event-based)
    await planningModePromise;
    
    // Also verify planning tabs are visible as a fallback
    const planningTabs = page.getByRole("tablist", { name: "World planning views" });
    await expect(planningTabs).toBeVisible({ timeout: 3000 });
    
    // For "NoSplashWorld", ensure it has no splash image
    if (worldName === "NoSplashWorld") {
      // Wait for the world header to render - wait for settings button to be visible
      const settingsButton = page.getByRole("button", { name: "World settings" });
      const settingsVisible = await settingsButton.isVisible({ timeout: 3000 }).catch(() => false);
      
      if (settingsVisible) {
        // Check if there's an image in the world header (indicates splash image is set)
        // Look for img element near the settings button
        const worldHeaderArea = page.locator("section").filter({ has: settingsButton }).first();
        const hasImage = await worldHeaderArea.locator("img").first().isVisible().catch(() => false);
        
        if (hasImage) {
          // World has a splash image - open settings to clear it
          await settingsButton.click();
          await expect(page.getByRole("dialog", { name: "World Settings" })).toBeVisible({ timeout: 3000 });
          
          // Find and click the Clear button
          const clearButton = page.getByRole("button", { name: "Clear" });
          await expect(clearButton).toBeVisible({ timeout: 2000 });
          
          // Set up event listeners BEFORE clicking Clear
          const worldUpdatedPromise = waitForWorldUpdated(page, undefined, "splashImageCleared", 10000);
          
          // Click Clear - this should trigger setWorldSettingsOpen(false) and close the modal
          await clearButton.click();
          
          // Wait for world update event (splash image cleared)
          // The modal should close automatically, but we care more about the world update
          await worldUpdatedPromise.catch(() => {
            // If event doesn't fire, that's okay - the important thing is the splash is cleared
            // which will be verified later in the test
          });
        }
        // If no image, no need to open settings - world already has no splash image
      }
    }
  } else {
    // If neither exists, try to click anyway (might be in DOM but not visible)
    await worldTab.click({ force: true }).catch(() => {
      throw new Error(`World "${worldName}" (or "${finalWorldName}") not found`);
    });
  }
});

When("the admin selects world {string}", async ({ page }, worldName: string) => {
  // Ensure user is logged in first
  const logoutButton = page.getByRole("button", { name: "Log out" });
  const isLoggedIn = await logoutButton.isVisible({ timeout: 1000 }).catch(() => false);
  if (!isLoggedIn) {
    await loginAs(page, "admin", "admin");
  }
  
  await ensureModeSelectorVisible(page);

  // Get the unique world name if it was stored, otherwise generate it (for "Eldoria" and "NoSplashWorld")
  let uniqueWorldName = worldName;
  if (worldName === "Eldoria" || worldName === "NoSplashWorld") {
    try {
      const storedName = await page.evaluate(() => {
        return (window as any).__testWorldName;
      });
      if (storedName) {
        uniqueWorldName = storedName;
      } else {
        uniqueWorldName = getUniqueCampaignName(worldName);
      }
    } catch {
      uniqueWorldName = getUniqueCampaignName(worldName);
    }
  }

  const worldContextTablist = page.getByRole("tablist", { name: "World context" });
  // Try unique name first, then fall back to base name
  let worldTab = worldContextTablist.getByRole("tab", { name: uniqueWorldName });
  let exists = await worldTab.isVisible().catch(() => false);
  
  if (!exists && (worldName === "Eldoria" || worldName === "NoSplashWorld")) {
    // Fall back to base name for backwards compatibility
    worldTab = worldContextTablist.getByRole("tab", { name: worldName });
    exists = await worldTab.isVisible().catch(() => false);
  }
  
  if (exists) {
    // Set up event listener BEFORE clicking
    const planningModePromise = waitForPlanningMode(page, 5000);
    
    await worldTab.click();
    
    // Wait for planning mode to activate (event-based)
    await planningModePromise;
    
    // Also verify planning tabs are visible as a fallback
    const planningTabs = page.getByRole("tablist", { name: "World planning views" });
    await expect(planningTabs).toBeVisible({ timeout: 3000 });
    
    // For "NoSplashWorld", ensure it has no splash image
    if (worldName === "NoSplashWorld") {
      // Wait for the world header to render - wait for settings button to be visible
      const settingsButton = page.getByRole("button", { name: "World settings" });
      const settingsVisible = await settingsButton.isVisible({ timeout: 3000 }).catch(() => false);
      
      if (settingsVisible) {
        // Check if there's an image in the world header (indicates splash image is set)
        // Look for img element near the settings button
        const worldHeaderArea = page.locator("section").filter({ has: settingsButton }).first();
        const hasImage = await worldHeaderArea.locator("img").first().isVisible().catch(() => false);
        
        if (hasImage) {
          // World has a splash image - open settings to clear it
          await settingsButton.click();
          await expect(page.getByRole("dialog", { name: "World Settings" })).toBeVisible({ timeout: 3000 });
          
          // Find and click the Clear button
          const clearButton = page.getByRole("button", { name: "Clear" });
          await expect(clearButton).toBeVisible({ timeout: 2000 });
          
          // Set up event listeners BEFORE clicking Clear
          const worldUpdatedPromise = waitForWorldUpdated(page, undefined, "splashImageCleared", 10000);
          
          // Click Clear - this should trigger setWorldSettingsOpen(false) and close the modal
          await clearButton.click();
          
          // Wait for world update event (splash image cleared)
          // The modal should close automatically, but we care more about the world update
          await worldUpdatedPromise.catch(() => {
            // If event doesn't fire, that's okay - the important thing is the splash is cleared
            // which will be verified later in the test
          });
        }
        // If no image, no need to open settings - world already has no splash image
      }
      
      // Note: We don't strictly verify the modal is closed here because:
      // 1. The Clear button should close it automatically (calls setWorldSettingsOpen(false))
      // 2. If there's a React state timing issue, the modal might still be visible
      // 3. The important thing is that the splash image is cleared, which will be verified
      //    by the test's "Then" step checking for the placeholder
      // 4. If the world still has a splash image, the test will fail later
    }
  } else {
    // If neither exists, try to click anyway (might be in DOM but not visible)
    await worldTab.click({ force: true }).catch(() => {
      throw new Error(`World "${worldName}" (or "${uniqueWorldName}") not found`);
    });
  }
});

When("the admin navigates to the creatures tab", async ({ page }) => {
  // Ensure planning tabs are visible (world must be selected)
  const planningTabs = page.getByRole("tablist", { name: "World planning views" });
  await expect(planningTabs).toBeVisible({ timeout: 5000 });
  
  await expect(page.getByRole("tab", { name: "Creatures" })).toBeVisible({ timeout: 3000 });
  await page.getByRole("tab", { name: "Creatures" }).click();
  await expect(page.getByRole("button", { name: "Add creature" })).toBeVisible({ timeout: 3000 });
});

When('the admin ensures creature "Dragon" exists', async ({ page }) => {
  const hasDragon = await page
    .getByRole("listitem")
    .filter({ hasText: "Dragon" })
    .first()
    .isVisible()
    .catch(() => false);

  if (!hasDragon) {
    await page.getByRole("button", { name: "Add creature" }).click();
    await expect(page.getByRole("dialog", { name: "Add creature" })).toBeVisible({ timeout: 3000 });

    await page.getByLabel("Creature name").fill("Dragon");
    await page.getByLabel("Summary").fill("A fearsome fire-breathing beast.");
    await page.getByRole("button", { name: "Save creature" }).click();
    
    // Wait for modal to close and creature to appear
    await expect(page.getByRole("dialog", { name: "Add creature" })).toBeHidden({ timeout: 3000 });
    await expect(
      page.getByRole("listitem").filter({ hasText: "Dragon" }).first()
    ).toBeVisible({ timeout: 3000 });
  }
});

Then('creature "Dragon" appears in the creatures list', async ({ page }) => {
  await expect(
    page.getByRole("listitem").filter({ hasText: "Dragon" }).first()
  ).toBeVisible({ timeout: 3000 });
});

When("the admin navigates to the factions tab", async ({ page }) => {
  await page.getByRole("tab", { name: "Factions" }).click();
  await expect(page.getByRole("button", { name: "Add faction" })).toBeVisible();
});

When('the admin ensures faction "Order of the Flame" exists', async ({ page }) => {
  const hasFaction = await page
    .getByRole("listitem")
    .filter({ hasText: "Order of the Flame" })
    .first()
    .isVisible()
    .catch(() => false);

  if (!hasFaction) {
    await page.getByRole("button", { name: "Add faction" }).click();
    await expect(page.getByRole("dialog", { name: "Add faction" })).toBeVisible();

    await page.getByLabel("Faction name").fill("Order of the Flame");
    await page.getByLabel("Summary").fill("A secretive order of mages.");
    await page.getByRole("button", { name: "Save faction" }).click();
  }
});

Then('faction "Order of the Flame" appears in the factions list', async ({ page }) => {
  await expect(
    page.getByRole("listitem").filter({ hasText: "Order of the Flame" }).first()
  ).toBeVisible();
});
